### ISSUE TITLE
Add support for unliking a song

### ISSUE THREAD

**Issue by Keith94** [JohannesFischer/soundcloud-control#1]
Nice add-on, I'm a fan. 👍 

I didn't see the ability to unlike a song you've already liked. I think it'd be nice to have. Can that be implemented?

**Comment by JohannesFischer** [comment]
Hi, thanks for your feedback.

That sure is possible but since there is no way to tell if the song is already liked or not that would be an additional entry in the context menu of the extension.  Kind of the opposite of the like current song option, that unlikes the current song if it has been liked before.

I will definitely look into that when I find the time.

**Comment by Keith94** [comment]
That sounds reasonable. :)

What if you replaced the whole context menu with a panel featuring playback controls (icons and text)? Just an idea.

**Comment by JohannesFischer** [comment]
I wanted to keep the extension as simple as possible and having all options as icons in the toolbar would take quiet a bit of space. But I am planning to have the controls in a popup instead of the context menu, somewhat like this:
![popup](https://mdn.mozillademos.org/files/14039/popup-shadow.png)

**Comment by Keith94** [comment]
Yes popup is what I meant. I like that.

Make the controls look like official SC ones?

![image](https://user-images.githubusercontent.com/5490615/33104706-50698d18-cede-11e7-98ea-43cbe4ceec7d.png)

**Comment by JohannesFischer** [comment]
Sure, I'd use a similar style as the player controls on the SoundCloud page.

Will investigate if there's a way to get the player state before getting started on this but furst I can add the unlike option to the context menu.

Will keep you updated on the progress.

**Comment by JohannesFischer** [comment]
I just uploaded the update, adding the option to unlike the song currently playing. Update your addon to 0.1.0 and enjoy. 

Cheers.
