### ISSUE TITLE
Please add the lighter button

### ISSUE THREAD

**Issue by survivor303** [JohannesFischer/soundcloud-control#10]
I hope that you find time to fix the icon issue on the toolbar.
It not are great for now with dark theme.
![soundcloud-control](https://user-images.githubusercontent.com/3097696/41874340-545d2398-78d0-11e8-95c5-0b315baebc1f.png)

**Comment by JohannesFischer** [comment]
@survivor303 I added a lighter icon for the dark theme in the 0.5.3 release. Please check it out and let me know in case you are having any issues with that.
