### ISSUE TITLE
Panel doesn't adapt to multiple tabs

### ISSUE THREAD

**Issue by Keith94** [JohannesFischer/soundcloud-control#3]
Hi @JohannesFischer 

Great work on the new popup/panel design, it looks excellent! :)

I wanted to report a possible bug with it though.

1. Open two soundcloud tabs (e.g. open https://soundcloud.com/stream twice)
2. Play a song in tab 1
3. Switch to tab 2 and play a different song
4. Open the soundcloud control panel

At this point the add-on doesn't reflect the new song that's being played, so it still shows the old song. Any chance for a fix? Thanks!

**Comment by JohannesFischer** [comment]
Hi,

thanks for your feedback and I'm glad your like the popup and the appearance.

Usually I just have one tab open but I can see that this can make the extension work in an unexpected way. At the moment the extension will find the first tab matching a SoundCloud URL and will use its content for the popup, any other SoundCloud tabs.

What I could do, is to additionally check for other tabs matching a SoundCloud URL AND is currently playing media - which is indicated by a speaker icon in the tab.

**Comment by Keith94** [comment]
Sounds good man, I hope you add that in the next release :-)

**Comment by JohannesFischer** [comment]
Had a look at this and it seems to work okay with multiple tabs as long as one is audible, otherwise it falls back to the first tab found.

Will test the changes for some time and add the changes to the next release.

**Comment by JohannesFischer** [comment]
Just release 0.4 which should handle multiple tabs much better. It prioritizes the audible SoundCloud tab. Please update your extension and let me know if you have any issues.
